# Generated by Django 4.0.3 on 2022-03-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubbroker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='name',
        ),
    ]
