# Generated by Django 4.0.3 on 2022-03-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_clubbroker_profile_pic_company_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
