# Generated by Django 4.0.3 on 2022-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('serialnumber', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('warranty', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
