# Generated by Django 4.0.3 on 2022-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_work_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
