# Generated by Django 4.0.3 on 2022-03-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_work_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='serialnumber',
            new_name='serial_number',
        ),
    ]
