# Generated by Django 4.0.3 on 2022-03-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_rename_serialnumber_work_serial_number'),
        ('account', '0007_engineer_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.engineer')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.work')),
            ],
        ),
    ]
