# Generated by Django 3.2.10 on 2022-04-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_alter_applywork_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='reports', verbose_name='Report')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.applywork')),
            ],
        ),
    ]
