# Generated by Django 4.0.1 on 2022-03-16 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('warranty', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
